trigger:
- none

pool:
  vmImage: 'windows-latest'

steps:
- task: UseDotNet@2
  inputs:
    packageType: 'sdk'
    version: '9.x'

- task: NuGetToolInstaller@1  # Ensure NuGet CLI is installed

- task: DotNetCoreCLI@2
  inputs:
    command: 'restore'
    restoreSolution: '**/G9.Redis.Trigger*.csproj'

- task: DotNetCoreCLI@2
  inputs:
    command: 'pack'
    packagesToPack: '**/G9.Redis.Trigger*.csproj'
    buildProperties: 'Configuration=Release;Version=${{ Build.BuildNumber }};PackageVersion=${{ Build.BuildNumber }}'

- task: DotNetCoreCLI@2
  inputs:
    command: 'push'
    packagesToPush: '**/G9.Redis.Trigger*.nupkg'
    nuGetFeedType: 'internal'
    publishVstsFeed: 'G9.Redis/g9-redis-feed'
    allowPackageConflicts: true

